env:
  global:
    - GH_REF: github.com/Turbo87/open-flight-planner.git
    - secure: nfYanP/hg89b07eEGd1MrDaJpEKh681K3v9TxkQMj368DAzyqod91hhuFhJifg+ro1dHiQbmZI6lnd86C3kEbX5I5gUnVXU6ce21gDDFWsfhcTTtsljO0nrH/40b/327F5CWUpWpB79LOHmu39InWI1zisXVHYUPdK6ecOGARIW28Gy7yrb8HmFzVsHn7HijfEj+WNkT8blB0/Uj7lB2S+jSFHL7WywFI1NwP9NZSow4YESXjdkdmP1CZHZfmB8NkC9Vm/qsJxVVj4/xWrczYt9OrwxbXc31rdCdKnnpQ0VbVFGqsMJp3eXyjhQuoWAnYWXW1f6dLQLvi3OJ2DGV6DlpRWU5jEBpPbKAefegz/V99wncs7J0aU8diiy0RBvNcY9GwZV6D1kCiTXNu9wU5xwxTPFKa1nN/zh/dcUdIswCf04y12dNUjea2kLnUPx5EYZ0nnGw3ORxWBry77c0OF8rsjjo7PD3VH6fWziGDMM0REcST17rnGAAihK8iG0l6tx28cRGFy+cpY2rZ4x3tnL//jA9UR/o9u7tvGC9f5/KRb7sRZPI72AsT1a08b9xo3S94JFV2bqpxuiySgppas56YsfgvJq1l7J4Li7KXnuN4zDG92uqjTSL1kn5DkUcUWniz91BrjAlroUDEygzSM5Nmxzq2PvrEkQD3kTLMsY=

install: npm install
script: bash ./deploy.sh
